area_create:
  path: /create
  defaults: { _controller: "AppBundle:Area:create" }
  methods: POST

area_view:
  path: /view
  defaults: { _controller: "AppBundle:Area:view" }
  methods: GET

area_get:
  path: /get/{id}
  defaults: { _controller: "AppBundle:Area:getOne", id:null }
  methods: GET

area_edit:
  path: /edit/{id}
  defaults: { _controller: "AppBundle:Area:edit", id:null }
  methods: POST

area_delete:
  path: /delete/{id}
  defaults: { _controller: "AppBundle:Area:delete", id:null }
  methods: DELETE