# el homepage reemplaza al name="" del Route
homepage:
  path: /
  defaults: { _controller: "AppBundle:Default:index" }
  methods: GET

login:
  path: /login
  defaults: { _controller: "AppBundle:Default:login" }
  methods: POST